#import "./PlayerFragment.gql"

mutation createMatch($input: MatchInput!) {
  createMatch(input: $input) {
    id
    winner{
      playerA{...Player}
      playerB{...Player}
    }
    looser{
      playerA{...Player}
      playerB{...Player}
    }
    timestamp
  }
}
