#import "./PlayerFragment.gql"

{ 
    matches {
    id
    winner{
      playerA{...Player}
      playerB{...Player}
    }
    looser{
      playerA{...Player}
      playerB{...Player}
    }
    timestamp
    }
}